Repository Specshell/specshell.software.maven.pom, pull requests merged in 2020-12, with the labels that each got.

#12 allow spring boot version override
  pom.xml
Labels: enhancement

#15 Revert "Bump maven-surefire-plugin from 3.0.0-M4 to 3.0.0-M5"
  pom.xml
Labels: bug

#18 use release flag instead of source/target
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  pom.xml
Labels: enhancement

#19 update bom to v0.1.23
  pom.xml
Labels: dependencies

#20 update bom to 0.1.24
  pom.xml
Labels: dependencies

#21 bump bom to 0.1.25
  pom.xml
Labels: dependencies

#22 publish to maven central
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  LICENSE
  pom.xml
Labels: enhancement

#27 bump bom to 0.1.28
  pom.xml
Labels: dependencies

#28 use latest bom with new siba-models
  pom.xml
Labels: dependencies
